### ISSUE TITLE
Unit Test No-Op from Cul::Hydra::Solrizer::ModsFieldable when no MODS

### ISSUE THREAD

**Issue by barmintor** [cul/cul_scv_hydra#10]
Verify that #to_solr does nothing if there's no mods - this can be done with a simple test rig, it doesn't even need to be a AF object

**Comment by elo2112** [comment]
Will this work?

https://github.com/cul/cul_scv_hydra/commit/b1a4845fa31065dcb37a1028c52665bc1336ad46

**Comment by barmintor** [comment]
That looks good, presuming you want the whitespace you added in the impl.

- B

**Comment by elo2112** [comment]
Great, thanks.  Yeah, that's a lot more whitespace showing up on GitHub than in my local copy.  Just removed the new line.
