### ISSUE TITLE
Unit Tests for Geo indexing

### ISSUE THREAD

**Issue by barmintor** [cul/cul_scv_hydra#9]
There's no test coverage for Cul::Hydra::Solrizer::ModsFieldable#coordinates 
https://github.com/cul/cul_scv_hydra/blob/master/lib/cul_hydra/solrizer/mods_fieldable.rb#L302

**Comment by elo2112** [comment]
Added!

https://github.com/cul/cul_scv_hydra/commit/e696990aa643dbbfbba3f6653a8e5a3bb884c35b
